### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by kevinzhao4939** [EdwinWu1423/diligent-computing#2]
statement of problem: the problem seems fine. isn't this what mr. holmes had in class when we were doing it together?

recursive abstraction: i agree with most of this, but i'm kind of confused when you added "a maze of n choices" and "a maze of n-1 choices". i didn't understand how a maze can have choices and what those choices are. could you have meant paths or stepping stones? for example, when trying to see if a maze of 10 "choices" or stepping stones is navigable, the recursive abstraction can see if a maze of one "choice" smaller, or a maze with 9 stepping stones, is navigable. this is what i get from it but i don't know if it's what you intended. 

base case: i think the base case is fine, which returns true only when the explorer is on top of the treasure. i have it so it will return true if the treasure is one stepping stone away from the treasure, but i guess any way is fine. 

english or pseudocode description of algorithm: what happens when the algorithm needs to back track? for example if it's chooses the wrong path in an intersection? i just had it backtrack its steps until the intersection and have it change course, but i'm confused as to where it does this in your code. everything else looks very good; i like how you moved the explorer position into a newer position, but i would keep the explorer position at every intersection so i could go back to them.

**Comment by tinawong15** [comment]
Thank you for taking the time to read our README.md. We tried to incorporate your suggestions. Please reopen the issue if any of the English still remains unclear.
